# name of workflow
name: Deploy to VPS

# when to run
on:
  push:
    branches:
      - main

# the work to do
jobs:
  deploy: # name of job
    runs-on: ubuntu-latest # OS to use for runner

    steps: # list of steps to do in order
      - name: Checkout code
        uses: actions/checkout@v4 # clones repo onto runner

      - name: Setup Node
        uses: actions/setup-node@v4 # installs node on the runner
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci # npm install for CI environment

      - name: Build
        run: npm run build

      - name: Set up SSH
        # store ssh key from secrets and add VPS fingerprint to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        # rsync build to VPS
        run: |
          rsync -avz --delete \
          -e "ssh -i ~/.ssh/deploy_key" \
          dist/ \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/linettekuhn.com
